export const COMMENT_ADD = 'COMMENT_ADD';
export const COMMENT_REMOVE = 'COMMENT_REMOVE';
export const COMMENT_FIELD_CHANGE = 'COMMENT_FIELD_CHANGE';
export const COMMENTS_CLEAR = 'COMMENTS_CLEAR';
export const COMMENT_THUMB_UP = 'COMMENT_THUMB_UP';
export const COMMENT_THUMB_DOWN = 'COMMENT_THUMB_DOWN';
export const COMMENTS_CLEAR_INPUT = 'COMMENTS_CLEAR_INPUT';
